### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by keyboqrd** [markerikson/redux-quickstart-example-app#66] opened 2023-09-23 06:25 UTC
master branch.

I did `yarn install`, then replaced `start` in package.json with `react-scripts --openssl-legacy-provider start`

then i went yarn start, here is the error:

```
Failed to compile.

./node_modules/headers-polyfill/lib/index.mjs 259:53
Module parse failed: Unexpected token (259:53)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     this[_a] = {};
|     this[_b] = /* @__PURE__ */new Map();
>     if (["Headers", "HeadersPolyfill"].includes(init?.constructor.name) || init instanceof HeadersPolyfill) {
|       const initialHeaders = init;
|       initialHeaders.forEach((value, name) => {
```

**Comment by 4theLoveofForms** [comment] 2023-09-26 16:42
I have the same error.  I tried changing the node version back to 16 --lts, but no luck

**Comment by theLaurynas** [comment] 2023-10-10 07:47
Any luck on fixing this?

**Comment by Shantanu2706** [comment] 2023-10-16 07:10
Any luck on fixing this ?

**Comment by 4theLoveofForms** [comment] 2023-10-17 12:55
I cloned this guy's fork, hes fixed it but it hasnt been merged yet, which worked for me  https://github.com/ronycage/redux-essentials-example-app/tree/master  (i think it was him it was a little while ago..)

**Comment by markerikson** [comment] 2023-10-17 12:59
It would help if someone could narrow down _which_ package is having an issue here.

**Comment by denspiro** [comment] 2023-10-18 12:08
The issue is still in the `master`. Would be nice if maintainers will check it.

**Comment by markerikson** [comment] 2023-10-18 12:23
@denspiro : I just said, it would be helpful if people could identify _what_ package is actually causing a problem here.

I have a lot of other things on my plate, and unfortunately I don't have time to look into this myself any time soon.  If you can provide more details on what specifically needs to be updated, I _might_ be able to make a tweak, but just complaining isn't going to fix anything.

**Comment by markerikson** [comment] 2024-02-01 03:54
FYI, I've migrated the example app codebase to use Vite and updated all dependencies.  It should now work correctly on Node 18+.

**Closed as completed by markerikson** 2024-02-01 03:54 UTC
